
apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: flask-test-app1
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app1
spec:
  selector:
    matchLabels:
      app: flask-test-app1
  replicas: 5
  template:
    metadata:
      labels:
        app: flask-test-app1
    spec:
      containers:
      - name: flask-test-app1
        image: runner1.home.local:5000/myadmin/flask-test-app1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000