
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: test-app2
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app2
spec:
  selector:
    matchLabels:
      app: test-app2
  replicas: 5
  template:
    metadata:
      labels:
        app: test-app2
    spec:
      containers:
      - name: test-app2
        image: runner1.home.local:5000/myadmin/test-app2:v5
        imagePullPolicy: Always
        ports:
        - containerPort: 5000