name: CI/CD
on: push

jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image # push The image to the docker hub
        run: docker build . --file Dockerfile --tag localhost:5000/myadmin/flask-test-app:latest

      - name: Docker Push
        run: docker image push localhost:5000/myadmin/flask-test-app:latest

  deploy:
    name: Deploy
    needs: Build 
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

    
      - name: Set Kubernetes Context
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete -f kubernetes/deployment.yaml
...
