name: CI/CD
on: push

jobs:

  clear-cache:
      runs-on: self-hosted
      steps:
        - name: Clear cache
          uses: actions/github-script@v6
          with:
            script: |
              console.log("About to clear")
              const caches = await github.rest.actions.getActionsCacheList({
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
              for (const cache of caches.data.actions_caches) {
                console.log(cache)
                github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
              }
              console.log("Clear completed")

  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image # push The image to the docker hub
        run: docker build . --file Dockerfile --tag localhost:5000/myadmin/test-app2:latest

      - name: Docker Push
        run: |
         docker rmi localhost:5000/myadmin/test-app2
         docker image push localhost:5000/myadmin/test-app2:latest
        

  deploy:
    name: Deploy
    needs: Build 
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
    
      - name: Set Kubernetes Context
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f kubernetes/deployment.yaml
...
