name: CI/CD

on: push

jobs:
  test:
    name: Test
    runs-on: Runner1
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Php
        uses: "shivammathur/setup-php@v2"
        with:
         php-version: "latest"

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Execute database migrations
        run: bin/console doctrine:migrations:diff --no-interaction

      - name: Run tests
        run: make check

  build:
    name: Build
    needs: test
    runs-on: Runner1
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ghcr.io/tassaing/my-image-name:t10
          build-args: |
              "NPM_TOKEN=${{ secrets.TOKEN }}"
          push: true

  deploy:
    name: Deploy
    needs: build 
    runs-on: Runner1
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

    
      - name: Set Kubernetes Context
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f kubernetes/deployment.yaml
...
