name: CI/CD

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      database:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
        ports:
          - 3306:3306
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Execute database migrations
        run: bin/console doctrine:migrations:diff --no-interaction

      - name: Run tests
        run: make check

  build:
    name: Build
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ghcr.io/tassaing/my-image-name:t10
          build-args: |
              "NPM_TOKEN=${{ secrets.TOKEN }}"
          push: true

  deploy:
    name: Deploy
    #needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

    
      - name: Kubernetes Deployment
        uses: danielr1996/kubectl-action@1.0.0
        with:
         kubeconfig: ${{ secrets.KUBE_CONFIG }}
         args: apply -f kubernetes/deployment.yaml
...
